import SwiftUI

struct AboutView: View {
    @AppStorage("apiBaseURL") private var apiBaseURLOverride: String = ""

    private var appVersion: String {
        let version = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "1.0"
        let build = Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "1"
        return "\(version) (\(build))"
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    VStack(spacing: 8) {
                        Image(systemName: "wand.and.stars")
                            .font(.system(size: 40))
                            .foregroundStyle(Color.accentColor)
                        Text("Itinera")
                            .font(.title2.weight(.bold))
                        Text("AI-powered trip planning built around trending places.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 8)
                }

                Section("About your itineraries") {
                    Text("Itineraries are generated by AI from trending travel spots. Details like opening hours, prices, and exact addresses can be wrong or out of date — always double-check before you go.")
                        .font(.subheadline)
                }

                Section("Privacy") {
                    Text("Trip details you enter (destination, dates, preferences) are sent to our server to build your itinerary. Saved trips are stored only on this device.")
                        .font(.subheadline)
                    // TODO: replace with the real hosted privacy policy before submission.
                    Link("Privacy Policy", destination: URL(string: "https://itinera.example.com/privacy")!)
                    Link("Contact Support", destination: URL(string: "mailto:support@itinera.example.com")!)
                }

                Section("Developer") {
                    TextField("API base URL override", text: $apiBaseURLOverride)
                        .keyboardType(.URL)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                    LabeledContent("Active server", value: APIClient.baseURL.absoluteString)
                        .font(.footnote)
                }

                Section {
                    LabeledContent("Version", value: appVersion)
                }
            }
            .navigationTitle("About")
        }
    }
}

#Preview {
    AboutView()
}
